import type { CatalogModel, Oem, SpecificationDefinition } from "./types";

export const previewOems: Oem[] = [
  { id: "oem-jetour", name: "Jetour", code: "JETOUR" },
  { id: "oem-soueast", name: "Soueast", code: "SOUEAST" },
  { id: "oem-kaiyi", name: "Kaiyi", code: "KAIYI" },
];

export const specificationDefinitions: SpecificationDefinition[] = [
  { id: "spec-engine", category: "Performance", name: "Engine", unit: "L", isFilterable: true, status: "published" },
  { id: "spec-power", category: "Performance", name: "Power", unit: "hp", isFilterable: true, status: "published" },
  { id: "spec-drive", category: "Performance", name: "Drivetrain", unit: "", isFilterable: true, status: "published" },
  { id: "spec-seats", category: "Dimensions", name: "Seats", unit: "", isFilterable: true, status: "published" },
  { id: "spec-range", category: "Efficiency", name: "Electric range", unit: "km", isFilterable: true, status: "published" },
];

function spec(definitionId: string, displayValue: string, numericValue: number | null) {
  return { specificationDefinitionId: definitionId, displayValue, numericValue };
}

export const previewModels: CatalogModel[] = [
  {
    id: "model-t2",
    oemId: "oem-jetour",
    code: "T2",
    name: "T2",
    slug: "t2",
    bodyType: "suv",
    status: "published",
    versions: [
      {
        id: "ver-t2-2026",
        code: "2026",
        name: "T2 2026",
        modelYear: 2026,
        status: "published",
        contentSections: [
          { key: "overview", body: "Compact off-road SUV for the current model year." },
          { key: "exterior", body: "Squared lighting, roof rails, and 19-inch alloys." },
          { key: "interior", body: "Dual screens, leatherette seats, and a flat rear floor." },
          { key: "performance", body: "2.0T petrol with selectable terrain modes." },
          { key: "technology", body: "Adaptive cruise, 360 camera, and wireless CarPlay." },
          { key: "safety", body: "Six airbags and a full driver-assistance suite." },
          { key: "charging", body: "" },
          { key: "highlights", body: "Book a test drive at an Albisher branch." },
        ],
        media: [
          { id: "media-t2-hero", name: "T2 hero" },
          { id: "media-t2-exterior", name: "T2 exterior" },
          { id: "media-t2-interior", name: "T2 interior" },
        ],
        trims: [
          {
            id: "trim-t2-comfort",
            code: "COMFORT",
            name: "Comfort",
            powertrainType: "petrol",
            price: 89900,
            currencyCode: "SAR",
            status: "published",
            specifications: [
              spec("spec-engine", "1.5T", 1.5),
              spec("spec-power", "156 hp", 156),
              spec("spec-drive", "FWD", null),
              spec("spec-seats", "5", 5),
            ],
          },
          {
            id: "trim-t2-deluxe",
            code: "DELUXE",
            name: "Deluxe",
            powertrainType: "petrol",
            price: 99900,
            currencyCode: "SAR",
            status: "published",
            specifications: [
              spec("spec-engine", "2.0T", 2),
              spec("spec-power", "187 hp", 187),
              spec("spec-drive", "AWD", null),
              spec("spec-seats", "5", 5),
            ],
          },
          {
            id: "trim-t2-luxury",
            code: "LUXURY",
            name: "Luxury",
            powertrainType: "petrol",
            price: 112900,
            currencyCode: "SAR",
            status: "published",
            specifications: [
              spec("spec-engine", "2.0T", 2),
              spec("spec-power", "187 hp", 187),
              spec("spec-drive", "AWD", null),
              spec("spec-seats", "5", 5),
            ],
          },
        ],
      },
    ],
  },
  {
    id: "model-dashing",
    oemId: "oem-jetour",
    code: "DASHING",
    name: "Dashing",
    slug: "dashing",
    bodyType: "suv",
    status: "published",
    versions: [
      {
        id: "ver-dashing-2025",
        code: "2025",
        name: "Dashing 2025",
        modelYear: 2025,
        status: "published",
        contentSections: [
          { key: "overview", body: "Coupe-roof family SUV." },
          { key: "exterior", body: "Fastback profile and hidden door handles." },
          { key: "interior", body: "Panoramic roof and a 24-inch display pair." },
          { key: "performance", body: "1.5T and 1.6T petrol options." },
          { key: "technology", body: "" },
          { key: "safety", body: "" },
          { key: "charging", body: "" },
          { key: "highlights", body: "" },
        ],
        media: [{ id: "media-dashing-hero", name: "Dashing hero" }],
        trims: [
          {
            id: "trim-dashing-comfort",
            code: "COMFORT",
            name: "Comfort",
            powertrainType: "petrol",
            price: 74900,
            currencyCode: "SAR",
            status: "published",
            specifications: [
              spec("spec-engine", "1.5T", 1.5),
              spec("spec-power", "156 hp", 156),
              spec("spec-drive", "FWD", null),
              spec("spec-seats", "5", 5),
            ],
          },
          {
            id: "trim-dashing-luxury",
            code: "LUXURY",
            name: "Luxury",
            powertrainType: "petrol",
            price: 86900,
            currencyCode: "SAR",
            status: "published",
            specifications: [
              spec("spec-engine", "1.6T", 1.6),
              spec("spec-power", "197 hp", 197),
              spec("spec-drive", "FWD", null),
              spec("spec-seats", "5", 5),
            ],
          },
        ],
      },
    ],
  },
  {
    id: "model-x70",
    oemId: "oem-jetour",
    code: "X70PLUS",
    name: "X70 Plus",
    slug: "x70-plus",
    bodyType: "mpv",
    status: "draft",
    versions: [
      {
        id: "ver-x70-2026",
        code: "2026",
        name: "X70 Plus 2026",
        modelYear: 2026,
        status: "draft",
        contentSections: [],
        media: [],
        trims: [
          {
            id: "trim-x70-comfort",
            code: "COMFORT",
            name: "Comfort",
            powertrainType: "petrol",
            price: 79900,
            currencyCode: "SAR",
            status: "draft",
            specifications: [spec("spec-seats", "7", 7), spec("spec-drive", "FWD", null)],
          },
        ],
      },
    ],
  },
  {
    id: "model-s09",
    oemId: "oem-soueast",
    code: "S09",
    name: "S09",
    slug: "s09",
    bodyType: "suv",
    status: "published",
    versions: [
      {
        id: "ver-s09-2026",
        code: "2026",
        name: "S09 2026",
        modelYear: 2026,
        status: "published",
        contentSections: [
          { key: "overview", body: "Family electric SUV." },
          { key: "charging", body: "DC fast charge and an 11 kW home charger." },
          { key: "highlights", body: "Range and charging blocks stay on this version." },
        ],
        media: [{ id: "media-s09-hero", name: "S09 hero" }],
        trims: [
          {
            id: "trim-s09-long",
            code: "LONG-RANGE",
            name: "Long Range",
            powertrainType: "electric",
            price: 129900,
            currencyCode: "SAR",
            status: "published",
            specifications: [
              spec("spec-power", "204 hp", 204),
              spec("spec-drive", "RWD", null),
              spec("spec-seats", "5", 5),
              spec("spec-range", "520 km", 520),
            ],
          },
        ],
      },
    ],
  },
  {
    id: "model-x3",
    oemId: "oem-kaiyi",
    code: "X3PRO",
    name: "X3 Pro",
    slug: "x3-pro",
    bodyType: "suv",
    status: "inactive",
    versions: [
      {
        id: "ver-x3-2024",
        code: "2024",
        name: "X3 Pro 2024",
        modelYear: 2024,
        status: "inactive",
        contentSections: [],
        media: [],
        trims: [
          {
            id: "trim-x3-comfort",
            code: "COMFORT",
            name: "Comfort",
            powertrainType: "petrol",
            price: 62900,
            currencyCode: "SAR",
            status: "inactive",
            specifications: [
              spec("spec-engine", "1.5", 1.5),
              spec("spec-power", "116 hp", 116),
              spec("spec-seats", "5", 5),
            ],
          },
        ],
      },
    ],
  },
];
